Rerun notebooks; observe pygit2 error in git_graph
All notebooks are fine except `git_graph.ipynb`, which has this
error from `show('.')`:

    AttributeError                            Traceback (most recent call last)
    Cell In[4], line 1
    ----> 1 show('.')

    File c:\Users\ek\.virtualenvs\codegraph-lYh-r7nx\Lib\site-packages\typeguard\__init__.py:1033, in typechecked.<locals>.wrapper(*args, **kwargs)
       1031 memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
       1032 check_argument_types(memo)
    -> 1033 retval = func(*args, **kwargs)
       1034 try:
       1035     check_return_type(retval, memo)

    Cell In[3], line 18, in show(repo_path)
         14     short_message = commit.message.split('\n\n')[0]
         15     graph.node(commit.hex, label=f'{short_hash}\n{short_message}',
         16                shape='plain', fontname=NODE_LABEL_FONT, fontsize='12')
    ---> 18 visit(repo[repo.head.target])
         20 for child in repo.walk(repo.head.target):
         21     for parent in child.parents:

    File c:\Users\ek\.virtualenvs\codegraph-lYh-r7nx\Lib\site-packages\typeguard\__init__.py:1033, in typechecked.<locals>.wrapper(*args, **kwargs)
       1031 memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
       1032 check_argument_types(memo)
    -> 1033 retval = func(*args, **kwargs)
       1034 try:
       1035     check_return_type(retval, memo)

    Cell In[3], line 13, in show.<locals>.visit(commit)
         11     return
         12 commits.add(commit)
    ---> 13 short_hash = commit.hex[:7]
         14 short_message = commit.message.split('\n\n')[0]
         15 graph.node(commit.hex, label=f'{short_hash}\n{short_message}',
         16            shape='plain', fontname=NODE_LABEL_FONT, fontsize='12')

    AttributeError: '_pygit2.Commit' object has no attribute 'hex'

Where `show` (and thus its local function `visit`) are defined in
the immediately preceidng cell of the same notebook.